### ISSUE TITLE
You can use cep-promise

### ISSUE THREAD

**Issue by lucianopf** [MateusAndrade/use-cep-hook#1]
# Description

That's actually not an Issue, but rather an suggestion 😬 

Right now your hook relies only at ViaCep to reply to it's user, and if there's any outage at ViaCep your hook simply wont work.

In order to solve this you might update your integration to use https://www.npmjs.com/package/cep-promise that will simplify all your logic and also provide integration with:
- ViaCep
- Correios
- WideNet

The module will fetch the data form all providers and return as soon as at least one of the services reply =)

**Comment by MateusAndrade** [comment]
> # Description
> That's actually not an Issue, but rather an suggestion 😬
> 
> Right now your hook relies only at ViaCep to reply to it's user, and if there's any outage at ViaCep your hook simply wont work.
> 
> In order to solve this you might update your integration to use https://www.npmjs.com/package/cep-promise that will simplify all your logic and also provide integration with:
> 
> * ViaCep
> * Correios
> * WideNet
> 
> The module will fetch the data form all providers and return as soon as at least one of the services reply =)

Hey @lucianopf , thanks for that suggestion. I will give a look on that, btw what do you think about helping me out with that? 😸

**Comment by MateusAndrade** [comment]
> # Description
> That's actually not an Issue, but rather an suggestion 😬
> 
> Right now your hook relies only at ViaCep to reply to it's user, and if there's any outage at ViaCep your hook simply wont work.
> 
> In order to solve this you might update your integration to use https://www.npmjs.com/package/cep-promise that will simplify all your logic and also provide integration with:
> 
> * ViaCep
> * Correios
> * WideNet
> 
> The module will fetch the data form all providers and return as soon as at least one of the services reply =)

HEY @lucianopf , i don't know about this package. I will give a look and improve this with that. 💃 .

Btw thanks! 🙉 🙉 🙉

**Comment by lucianopf** [comment]
Awesome mate!! 

If you need any help integrating with this lib please feel free to ask me! 😬

**Comment by MateusAndrade** [comment]
Thanks @lucianopf , i just published a new version using `cep-promise`. 🎉
